name: DevSecOps Pipeline (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Detectar lenguaje automáticamente
      run: |
        if [ -f "package.json" ]; then
          echo "APP_LANG=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "APP_LANG=python" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "APP_LANG=java" >> $GITHUB_ENV
        else
          echo "No se detectó lenguaje automáticamente."
          exit 1
        fi

    - name: Configurar entorno e instalar dependencias si no están
      run: |
        if [ "$APP_LANG" = "python" ]; then
          if ! command -v pip3 >/dev/null; then
            sudo apt update
            sudo apt install -y python3-venv python3-pip
          fi
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || true
        elif [ "$APP_LANG" = "nodejs" ]; then
          if ! command -v npm >/dev/null; then
            sudo apt update
            sudo apt install -y nodejs npm
          fi
          npm install
        elif [ "$APP_LANG" = "java" ]; then
          if ! command -v mvn >/dev/null; then
            sudo apt update
            sudo apt install -y maven default-jdk
          fi
          mvn clean install
        fi

    - name: Inicializar CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ env.APP_LANG }}

    - name: Analizar con CodeQL
      uses: github/codeql-action/analyze@v3

    - name: Instalar Trivy
      run: |
        if ! command -v trivy >/dev/null; then
          sudo apt install -y wget gnupg lsb-release apt-transport-https
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy
        fi

    - name: Ejecutar Trivy (SBOM + SCA)
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Descargar OWASP ZAP 2.16.1
      run: |
        if [ ! -f "zap.tar.gz" ]; then
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.1/ZAP_2.16.1_Linux.tar.gz -O zap.tar.gz
        fi

    - name: Extraer y preparar ZAP
      run: |
        if [ ! -d "zap" ]; then
          tar -xzf zap.tar.gz
          mv ZAP_2.16.1 zap
          ln -s $(pwd)/zap/zap.sh zaproxy
        fi

    - name: Ejecutar la aplicación para escaneo DAST
      run: |
        if [ "$APP_LANG" = "python" ]; then
          source venv/bin/activate
          nohup python3 app.py &
        elif [ "$APP_LANG" = "nodejs" ]; then
          nohup npm start &
        elif [ "$APP_LANG" = "java" ]; then
          nohup java -jar target/*.jar &
        fi
        sleep 10

    - name: Escaneo DAST con ZAP si no existe reporte
      run: |
        if [ ! -f "zap_report.html" ]; then
          ./zaproxy -cmd -quickurl http://localhost:5000 -quickout zap_report.html || true
        else
          echo "Reporte ZAP ya existe, se omite escaneo."
        fi

    - name: Subir reporte ZAP si existe
      if: success() && exists('zap_report.html')
      uses: actions/upload-artifact@v4
      with:
        name: reporte-zap
        path: zap_report.html
