name: DevSecOps Pipeline (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Detectar lenguaje automáticamente
      run: |
        if [ -f "package.json" ]; then
          echo "APP_LANG=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "APP_LANG=python" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "APP_LANG=java" >> $GITHUB_ENV
        else
          echo "No se detectó lenguaje automáticamente."
          exit 1
        fi

    - name: Instalar dependencias del lenguaje
      run: |
        if [ "$APP_LANG" = "python" ]; then
          sudo apt update
          sudo apt install -y python3-venv python3-pip
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        elif [ "$APP_LANG" = "nodejs" ]; then
          sudo apt update
          sudo apt install -y nodejs npm
          npm install
        elif [ "$APP_LANG" = "java" ]; then
          sudo apt update
          sudo apt install -y maven default-jdk
          mvn clean install
        fi

    - name: Inicializar CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ env.APP_LANG }}

    - name: Analizar con CodeQL
      uses: github/codeql-action/analyze@v3

    - name: Instalar Trivy
      run: |
        sudo apt install -y wget gnupg lsb-release apt-transport-https
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt update
        sudo apt install -y trivy

    - name: Ejecutar Trivy
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Descargar OWASP ZAP (último release semanal)
      run: |
        if [ ! -f "zap.jar" ]; then
          echo "🔍 Buscando última versión de ZAP..."
          ZAP_URL=$(curl -s https://github.com/zaproxy/zaproxy/releases/latest | grep -oP 'href="[^"]*ZAP_WEEKLY_D-[^"]*\.jar' | head -n 1 | cut -d'"' -f2)
          if [ -z "$ZAP_URL" ]; then
            echo "❌ No se pudo encontrar la URL de ZAP."
            exit 1
          fi
          wget -O zap.jar "https://github.com$ZAP_URL" || {
            echo "❌ Falló la descarga de ZAP."
            exit 1
          }
        else
          echo "✅ ZAP ya está presente."
        fi

    - name: Ejecutar la aplicación para escaneo DAST
      run: |
        if [ "$APP_LANG" = "python" ]; then
          source venv/bin/activate
          nohup python3 app.py &
        elif [ "$APP_LANG" = "nodejs" ]; then
          nohup npm start &
        elif [ "$APP_LANG" = "java" ]; then
          nohup java -jar target/*.jar &
        fi
        sleep 10

    - name: Escaneo DAST con ZAP
      run: |
        mkdir -p reporte
        java -jar zap.jar -cmd -quickurl http://localhost:5000 -quickout reporte/zap_report.html || true

    - name: Subir reporte ZAP
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-zap
        path: reporte/
