name: DevSecOps Pipeline (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Detectar lenguaje automáticamente
      run: |
        if [ -f "package.json" ]; then
          echo "Lenguaje detectado: Node.js"
          echo "APP_LANG=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "Lenguaje detectado: Python"
          echo "APP_LANG=python" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "Lenguaje detectado: Java (Maven)"
          echo "APP_LANG=java" >> $GITHUB_ENV
        else
          echo "No se detectó lenguaje automáticamente."
          exit 1
        fi

    - name: Configurar entorno e instalar dependencias
      run: |
        sudo apt update
        if [ "$APP_LANG" = "python" ]; then
          sudo apt install -y python3-venv python3-pip
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        elif [ "$APP_LANG" = "nodejs" ]; then
          sudo apt install -y nodejs npm
          npm install
        elif [ "$APP_LANG" = "java" ]; then
          sudo apt install -y maven default-jdk
          mvn clean install
        fi

    - name: Inicializar CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ env.APP_LANG }}

    - name: Analizar con CodeQL
      uses: github/codeql-action/analyze@v3

    - name: Instalar Trivy (método alternativo estable)
      run: |
        sudo apt install -y curl rpm
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

    - name: Ejecutar Trivy (SBOM + SCA)
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Descargar OWASP ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0.jar -O zap.jar

    - name: Ejecutar la aplicación para escaneo DAST
      run: |
        if [ "$APP_LANG" = "python" ]; then
          source venv/bin/activate
          nohup python3 app.py > app.log 2>&1 &
        elif [ "$APP_LANG" = "nodejs" ]; then
          nohup npm start > app.log 2>&1 &
        elif [ "$APP_LANG" = "java" ]; then
          nohup java -jar target/*.jar > app.log 2>&1 &
        fi
        sleep 10

    - name: Escaneo DAST con ZAP
      run: |
        java -jar zap.jar -cmd -quickurl http://localhost:5000 -quickout zap_report.html || true

    - name: Subir reporte ZAP
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-zap
        path: zap_report.html
