name: DevSecOps Pipeline (Self-hosted)

on:
  push:
    branches:
      - main

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Detectar lenguaje autom치ticamente
        run: |
          if [ -f "package.json" ]; then
            echo "APP_LANG=nodejs" >> $GITHUB_ENV
          elif [ -f "requirements.txt" ]; then
            echo "APP_LANG=python" >> $GITHUB_ENV
          elif [ -f "pom.xml" ]; then
            echo "APP_LANG=java" >> $GITHUB_ENV
          else
            echo "No se detect칩 lenguaje autom치ticamente."
            exit 1
          fi

      - name: Instalar herramientas esenciales
        run: |
          sudo apt update
          sudo apt install -y wget curl

      - name: Instalar dependencias del lenguaje seg칰n APP_LANG
        run: |
          if [ "$APP_LANG" = "python" ]; then
            sudo apt install -y python3-venv python3-pip
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          elif [ "$APP_LANG" = "nodejs" ]; then
            sudo apt install -y nodejs npm
            npm install
          elif [ "$APP_LANG" = "java" ]; then
            sudo apt install -y maven default-jdk
            mvn clean install
          fi

      - name: Inicializar y ejecutar CodeQL (SAST)
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ env.APP_LANG }}
      - uses: github/codeql-action/analyze@v3

      - name: Instalar Trivy (SBOM + SCA)
        run: |
          sudo apt install -y gnupg lsb-release apt-transport-https
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] \
            https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy
      - name: Ejecutar Trivy
        run: trivy fs . --exit-code 0 --severity HIGH,CRITICAL || true

      - name: Descargar OWASP ZAP 2.16.1 (Linux)
        run: |
          echo "游댌 Descargando ZAP 2.16.1..."
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.1/ZAP_2.16.1_Linux.tar.gz -O zap.tar.gz

      - name: Extraer ZAP
        run: |
          tar -xzf zap.tar.gz
          mv ZAP_2.16.1 zap
          ln -sf "$(pwd)/zap/zap.sh" zaproxy

      - name: Ejecutar aplicaci칩n para escaneo DAST
        run: |
          if [ "$APP_LANG" = "python" ]; then
            source venv/bin/activate
            nohup python3 app.py > app.log 2>&1 &
          elif [ "$APP_LANG" = "nodejs" ]; then
            nohup npm start > app.log 2>&1 &
          elif [ "$APP_LANG" = "java" ]; then
            nohup java -jar target/*.jar > app.log 2>&1 &
          fi
          sleep 10
          curl -I http://localhost:5000 || echo "丘멆잺 La app no respondi칩"

      - name: Escanear con ZAP (DAST)
        run: |
          mkdir -p reporte
          ./zaproxy -cmd -quickurl http://localhost:5000 -quickout reporte/zap_report.html || true

      - name: Subir reporte ZAP
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-zap
          path: reporte/
