name: DevSecOps Pipeline (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Detectar lenguaje automáticamente
      run: |
        if [ -f "package.json" ]; then
          echo "APP_LANG=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "APP_LANG=python" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "APP_LANG=java" >> $GITHUB_ENV
        else
          echo "No se detectó lenguaje automáticamente."
          exit 1
        fi

    - name: Configurar entorno e instalar dependencias
      run: |
        if [ "$APP_LANG" = "python" ]; then
          which python3-venv || sudo apt install -y python3-venv
          which pip3 || sudo apt install -y python3-pip
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        elif [ "$APP_LANG" = "nodejs" ]; then
          which node || sudo apt install -y nodejs npm
          npm install
        elif [ "$APP_LANG" = "java" ]; then
          which mvn || sudo apt install -y maven default-jdk
          mvn clean install
        fi

    - name: Inicializar CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ env.APP_LANG }}

    - name: Analizar con CodeQL
      uses: github/codeql-action/analyze@v3

    - name: Instalar Trivy
      run: |
        if ! command -v trivy &> /dev/null; then
          sudo apt install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy
        fi

    - name: Ejecutar Trivy (SBOM + SCA)
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Descargar OWASP ZAP
      run: |
        if [ ! -f "zap.jar" ]; then
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0.jar -O zap.jar || {
            echo "❌ No se pudo descargar ZAP"; exit 1;
          }
        fi

    - name: Ejecutar la aplicación para escaneo DAST
      run: |
        if [ "$APP_LANG" = "python" ]; then
          source venv/bin/activate
          nohup python3 app.py > app.log 2>&1 &
        elif [ "$APP_LANG" = "nodejs" ]; then
          nohup npm start > app.log 2>&1 &
        elif [ "$APP_LANG" = "java" ]; then
          nohup java -jar target/*.jar > app.log 2>&1 &
        fi
        sleep 15
        curl -I http://localhost:5000 || echo "⚠️ La app no respondió"

    - name: Escaneo DAST con ZAP
      run: |
        java -jar zap.jar -cmd -quickurl http://localhost:5000 -quickout zap_report.html || echo "⚠️ ZAP terminó con errores, pero seguimos."

    - name: Verificar si el reporte se generó
      run: |
        if [ -f "zap_report.html" ]; then
          echo "✅ Reporte ZAP generado correctamente."
        else
          echo "⚠️ No se generó zap_report.html"
        fi

    - name: Subir reporte ZAP si existe
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-zap
        path: zap_report.html
