name: DevSecOps Local App Scanner

on:
  workflow_dispatch:

jobs:
  local-security-scan:
    runs-on: self-hosted

    steps:
    - name: Ejecutar análisis de seguridad local
      env:
        GH_TOKEN: ${{ secrets.REPORTES_TOKEN }}  # Token personal con permiso repo
      run: |
        # Directorios base
        BASE_DIR="/opt/apps-a-revisar"
        REPORT_DIR="/opt/devsecops-reportes"
        mkdir -p "$REPORT_DIR"

        # Limpieza de reportes anteriores
        rm -rf "$REPORT_DIR"/*

        # Crear entorno virtual para instalar trivy2html
        python3 -m venv /tmp/trivyenv
        source /tmp/trivyenv/bin/activate
        pip install --quiet trivy2html

        # Recorrer cada aplicación en apps-a-revisar
        for APP in "$BASE_DIR"/*; do
          [ -d "$APP" ] || continue
          APP_NAME=$(basename "$APP")
          APP_REPORT="$REPORT_DIR/$APP_NAME"
          mkdir -p "$APP_REPORT"
          cd "$APP" || continue

          # Detectar y analizar Python
          if [ -f "requirements.txt" ]; then
            [ -d "venv" ] || python3 -m venv venv
            source venv/bin/activate
            pip install --quiet -r requirements.txt || true
            deactivate
            gh codeql database create "$APP_REPORT/codeql-python-db" --language=python --source-root=. || true
          fi

          # Detectar y analizar Node.js
          if [ -f "package.json" ]; then
            [ -d "node_modules" ] || npm install --silent || true
            gh codeql database create "$APP_REPORT/codeql-node-db" --language=javascript --source-root=. || true
          fi

          # Detectar y analizar Java
          if [ -f "pom.xml" ]; then
            mvn install -DskipTests -q || true
            gh codeql database create "$APP_REPORT/codeql-java-db" --language=java --source-root=. || true
          fi

          # Ejecutar análisis de seguridad con Trivy
          trivy fs . --format json --output "$APP_REPORT/trivy-report.json" || true

          # Generar reporte HTML con trivy2html desde entorno virtual
          /tmp/trivyenv/bin/trivy2html -i "$APP_REPORT/trivy-report.json" -o "$APP_REPORT/trivy-report.html" || true

          # Subir reporte HTML al repositorio de reportes (GitHub Pages)
          cd /tmp
          rm -rf reportes_seguridad
          git clone https://x-access-token:${GH_TOKEN}@github.com/marco8961/reportes_seguridad.git
          cd reportes_seguridad

          mkdir -p "$APP_NAME"
          cp "$APP_REPORT/trivy-report.html" "$APP_NAME/"

          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add .
          git commit -m "Nuevo reporte de seguridad para $APP_NAME" || echo "Sin cambios que subir"
          git push

          echo "Reporte disponible en: https://marco8961.github.io/reportes_seguridad/$APP_NAME/trivy-report.html"
        done

        # Ruta local de respaldo
        echo "Reportes locales disponibles en: $REPORT_DIR"
