name: DevSecOps Pipeline (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Detectar lenguaje autom치ticamente
      run: |
        if [ -f "package.json" ]; then
          echo "Lenguaje detectado: Node.js"
          echo "APP_LANG=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "Lenguaje detectado: Python"
          echo "APP_LANG=python" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "Lenguaje detectado: Java (Maven)"
          echo "APP_LANG=java" >> $GITHUB_ENV
        else
          echo "No se detect칩 lenguaje autom치ticamente."
          exit 1
        fi

    - name: Instalar dependencias del lenguaje
      run: |
        if [ "$APP_LANG" = "python" ]; then
          if ! command -v pip &> /dev/null; then
            sudo apt update
            sudo apt install -y python3-venv python3-pip
          fi
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        elif [ "$APP_LANG" = "nodejs" ]; then
          if ! command -v npm &> /dev/null; then
            sudo apt update
            sudo apt install -y nodejs npm
          fi
          npm install
        elif [ "$APP_LANG" = "java" ]; then
          if ! command -v mvn &> /dev/null; then
            sudo apt update
            sudo apt install -y maven default-jdk
          fi
          mvn clean install
        fi

    - name: Inicializar CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ env.APP_LANG }}

    - name: Analizar con CodeQL
      uses: github/codeql-action/analyze@v3

    - name: Instalar Trivy
      run: |
        sudo apt install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt update
        sudo apt install -y trivy

    - name: Ejecutar Trivy (SBOM + SCA)
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Descargar OWASP ZAP
      run: |
        echo "游댌 Descargando ZAP 2.13.0..."
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0.jar -O zap.jar

    - name: Ejecutar la aplicaci칩n para escaneo DAST
      run: |
        if [ "$APP_LANG" = "python" ]; then
          source venv/bin/activate
          nohup python3 app.py &
        elif [ "$APP_LANG" = "nodejs" ]; then
          nohup npm start &
        elif [ "$APP_LANG" = "java" ]; then
          nohup java -jar target/*.jar &
        fi
        sleep 10

    - name: Escaneo DAST con ZAP
      run: |
        java -jar zap.jar -cmd -quickurl http://localhost:5000 -quickout zap_report.html || true

    - name: Subir reporte ZAP
      uses: actions/upload-artifact@v4
      with:
        name: reporte-zap
        path: zap_report.html
