name: DevSecOps Pipeline (Multi-language)

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Detectar lenguaje automáticamente
      id: detect
      run: |
        if [ -f "requirements.txt" ]; then
          echo "lang=python" >> $GITHUB_OUTPUT
        elif [ -f "package.json" ]; then
          echo "lang=node" >> $GITHUB_OUTPUT
        elif [ -f "pom.xml" ]; then
          echo "lang=java" >> $GITHUB_OUTPUT
        else
          echo "lang=desconocido" >> $GITHUB_OUTPUT
        fi

    - name: Instalar dependencias
      run: |
        if [ "${{ steps.detect.outputs.lang }}" = "python" ]; then
          pip install -r requirements.txt
        elif [ "${{ steps.detect.outputs.lang }}" = "node" ]; then
          npm install
        elif [ "${{ steps.detect.outputs.lang }}" = "java" ]; then
          mvn install
        else
          echo "Lenguaje no soportado en esta configuración" && exit 1
        fi

    - name: SAST con CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ steps.detect.outputs.lang }}

    - name: Ejecutar análisis CodeQL
      uses: github/codeql-action/analyze@v2

    - name: Instalar Trivy
      run: |
        sudo apt update
        sudo apt install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt update
        sudo apt install trivy -y

    - name: SCA / SBOM con Trivy
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Instalar y ejecutar ZAP DAST
      run: |
        sudo apt install snapd -y
        sudo snap install zaproxy --classic
        nohup YOUR_SERVER_COMMAND &   # ← Aquí tú debes poner cómo arrancar la app
        sleep 10
        zaproxy -cmd -quickurl http://localhost:5000 -quickout zap_report.html

    - name: Subir reporte ZAP
      uses: actions/upload-artifact@v4
      with:
        name: reporte-zap
        path: zap_report.html
