name: DevSecOps Pipeline (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Detectar lenguaje autom치ticamente
      run: |
        if [ -f "package.json" ]; then
          echo "APP_LANG=nodejs" >> $GITHUB_ENV
        elif [ -f "requirements.txt" ]; then
          echo "APP_LANG=python" >> $GITHUB_ENV
        elif [ -f "pom.xml" ]; then
          echo "APP_LANG=java" >> $GITHUB_ENV
        else
          echo "No se detect칩 lenguaje autom치ticamente."
          exit 1
        fi

    - name: Configurar entorno e instalar dependencias
      run: |
        if [ "$APP_LANG" = "python" ]; then
          sudo apt install -y python3-venv python3-pip
          python3 -m venv venv
          source venv/bin/activate
          pip install --break-system-packages --upgrade pip
          pip install --break-system-packages -r requirements.txt
        elif [ "$APP_LANG" = "nodejs" ]; then
          sudo apt install -y nodejs npm
          npm install
        elif [ "$APP_LANG" = "java" ]; then
          sudo apt install -y maven default-jdk
          mvn clean install
        fi

    - name: Inicializar CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ env.APP_LANG }}

    - name: Analizar con CodeQL
      uses: github/codeql-action/analyze@v3

    - name: Instalar Trivy
      run: |
        sudo apt install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt update
        sudo apt install -y trivy

    - name: Ejecutar Trivy (SBOM + SCA)
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Instalar y correr OWASP ZAP
      run: |
        sudo apt install -y snapd
        sudo snap install zaproxy --classic

    - name: Ejecutar la aplicaci칩n para escaneo DAST
      run: |
        if [ "$APP_LANG" = "python" ]; then
          source venv/bin/activate
          nohup python3 app.py &
        elif [ "$APP_LANG" = "nodejs" ]; then
          nohup npm start &
        elif [ "$APP_LANG" = "java" ]; then
          nohup java -jar target/*.jar &
        fi
        sleep 10

    - name: Escaneo DAST con ZAP
      run: |
        zaproxy -cmd -quickurl http://localhost:5000 -quickout zap_report.html || true

    - name: Subir reporte ZAP
      uses: actions/upload-artifact@v4
      with:
        name: reporte-zap
        path: zap_report.html

    - name: Limpiar entorno para liberar espacio
      run: |
        sudo apt clean
        sudo rm -rf /var/lib/apt/lists/*
        rm -rf venv node_modules target
