name: DevSecOps Local App Scanner

on:
  workflow_dispatch:

jobs:
  local-security-scan:
    runs-on: self-hosted

    steps:
    - name: Ejecutar análisis de seguridad local
      env:
        GH_TOKEN: ${{ secrets.REPORTES_TOKEN }}  # Token personal con permiso repo
      run: |
        BASE_DIR="/opt/apps-a-revisar"
        REPORT_DIR="/opt/devsecops-reportes"
        mkdir -p "$REPORT_DIR"

        rm -rf "$REPORT_DIR"/*

        mkdir -p /tmp/templates
        wget -q -O /tmp/templates/report.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

        for APP in "$BASE_DIR"/*; do
          [ -d "$APP" ] || continue
          APP_NAME=$(basename "$APP")
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          APP_REPORT="$REPORT_DIR/$APP_NAME/$TIMESTAMP"
          mkdir -p "$APP_REPORT"
          cd "$APP" || continue

          if [ -f "requirements.txt" ]; then
            [ -d "venv" ] || python3 -m venv venv
            source venv/bin/activate
            pip install --quiet -r requirements.txt || true
            deactivate
            gh codeql database create "$APP_REPORT/codeql-python-db" --language=python --source-root=. || true
          fi

          if [ -f "package.json" ]; then
            [ -d "node_modules" ] || npm install --silent || true
            gh codeql database create "$APP_REPORT/codeql-node-db" --language=javascript --source-root=. || true
          fi

          if [ -f "pom.xml" ]; then
            mvn install -DskipTests -q || true
            gh codeql database create "$APP_REPORT/codeql-java-db" --language=java --source-root=. || true
          fi

          trivy fs . \
            --format template \
            --template "@/tmp/templates/report.tpl" \
            --output "$APP_REPORT/trivy-report.html" || true

          # Análisis DAST con OWASP ZAP
          if lsof -i :5000 >/dev/null 2>&1 || lsof -i :3000 >/dev/null 2>&1; then
            echo "DAST: Ejecutando OWASP ZAP..."
            docker run -u root --rm -v "$APP_REPORT:/zap/wrk" -t owasp/zap2docker-stable zap-baseline.py \
              -t http://localhost:5000 \
              -r dast-report.html || true
            mv "$APP_REPORT/dast-report.html" "$APP_REPORT/owasp-zap-report.html"
          else
            echo "DAST: No se detectó aplicación activa en localhost:5000 o 3000, se omite."
          fi

          cd /tmp
          rm -rf reportes_seguridad
          git clone https://x-access-token:${GH_TOKEN}@github.com/marco8961/reportes_seguridad.git
          cd reportes_seguridad

          mkdir -p "$APP_NAME"
          cp "$APP_REPORT/trivy-report.html" "$APP_NAME/"

          # Copiar también reporte de ZAP si existe
          if [ -f "$APP_REPORT/owasp-zap-report.html" ]; then
            cp "$APP_REPORT/owasp-zap-report.html" "$APP_NAME/"
          fi

          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add .
          git commit -m "Nuevo reporte de seguridad para $APP_NAME" || echo "Sin cambios que subir"
          git push

          echo "Reporte disponible en: https://marco8961.github.io/reportes_seguridad/$APP_NAME/trivy-report.html"
          if [ -f "$APP_REPORT/owasp-zap-report.html" ]; then
            echo "Reporte ZAP: https://marco8961.github.io/reportes_seguridad/$APP_NAME/owasp-zap-report.html"
          fi
        done

        echo "Reportes locales disponibles en: $REPORT_DIR"
